# Generated by Django 6.0.3 on 2026-04-12 01:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('mood_tag', models.CharField(blank=True, choices=[('grateful', 'Grateful'), ('anxious', 'Anxious'), ('hopeful', 'Hopeful'), ('sad', 'Sad'), ('proud', 'Proud'), ('overwhelmed', 'Overwhelmed'), ('calm', 'Calm'), ('angry', 'Angry'), ('confused', 'Confused'), ('happy', 'Happy')], max_length=20)),
                ('ai_sentiment_score', models.FloatField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_themes', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_checkin', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(default='🌙', max_length=10)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('year_of_study', models.CharField(blank=True, max_length=50)),
                ('subject_area', models.CharField(blank=True, max_length=100)),
                ('pronouns', models.CharField(blank=True, max_length=50)),
                ('streak_count', models.IntegerField(default=0)),
                ('last_checkin_date', models.DateField(blank=True, null=True)),
                ('total_checkins', models.IntegerField(default=0)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mood_score', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Neutral'), (4, 'Good'), (5, 'Great')])),
                ('mood_note', models.CharField(blank=True, max_length=500)),
                ('sleep_score', models.IntegerField(choices=[(1, 'Less than 4 hours'), (2, '4-6 hours'), (3, '6-7 hours'), (4, '7-8 hours'), (5, '8+ hours')])),
                ('stress_score', models.IntegerField(choices=[(1, 'Very High'), (2, 'High'), (3, 'Moderate'), (4, 'Low'), (5, 'None')])),
                ('stress_trigger', models.CharField(blank=True, max_length=200)),
                ('social_score', models.IntegerField(choices=[(1, 'Very isolated'), (2, 'Somewhat isolated'), (3, 'Neutral'), (4, 'Connected'), (5, 'Very connected')])),
                ('energy_score', models.IntegerField(choices=[(1, 'Exhausted'), (2, 'Tired'), (3, 'Okay'), (4, 'Energised'), (5, 'Very energised')])),
                ('mental_health_score', models.FloatField(blank=True, null=True)),
                ('ai_insight', models.TextField(blank=True)),
                ('ai_risk_flag', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MentalHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('avg_mood', models.FloatField(blank=True, null=True)),
                ('avg_sleep', models.FloatField(blank=True, null=True)),
                ('avg_stress', models.FloatField(blank=True, null=True)),
                ('avg_social', models.FloatField(blank=True, null=True)),
                ('avg_energy', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('ai_weekly_insight', models.TextField(blank=True)),
                ('ai_trend', models.CharField(blank=True, choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mh_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
