# Generated by Django 6.0.2 on 2026-06-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_userprofile_settings'),
        ('mood', '0003_userprofile_profile_picture'),
    ]

    operations = [
    ]
